# Set Zsh as default shell
set-option -g default-shell /bin/zsh
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # colored underscores
# set -as terminal-overrides ',alacritty:RGB' # true-color support

# enable passthrough for nvim mode based cursor shapes
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

# Enable mouse mode
set -g mouse on
set -g default-terminal "tmux-256color"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Themes
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# vim-like switching panels
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L
bind -r l select-pane -R 

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# don't rename windows automatically
set-option -g allow-rename off

# Set the numbering of windows to go from 1 instead of 0
set-option -g base-index 1
setw -g pane-base-index 1

# Load custom statusline theme
# source ~/.config/tmux/asteroid.tmux.sh
# Reduce command delay
set -sg escape-time 1

# Allow reload of Tmux configuration while using Tmux
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# vim like copy key bindings for tmux buffer
setw -g mode-keys vi
set-option set-clipboard on

# List of plugins
set -g @plugin 'catppuccin/tmux#v2.1.3' 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tmux/catppuccin.tmux'
